### ISSUE TITLE
Raiffeisen ELBA csv - once working, once not

### ISSUE THREAD

**Issue by lordvampire** [nblock/ofxstatement-austrian#12]
Hi,

i installed ofxstatement on Mac with home-brew and python3.9 and also your plugin. 

but getting the error `ValueError: time data '02.01.19' does not match format '%d.%m.%Y'`

i don't know how, but I got now one csv converted suddenly (opened csv in excel, textedit but did not change as far as I know anything) . A second csv I got from Elba bringing the same error now, but I don't know how to convert.. any help appreciated..

`faruktuefekli@Faruks-MBP ~ % sudo ofxstatement convert -t raiffeisen Downloads/1meinelba_umsaetze_AT113747500000176792_suche-2.csv statement3.ofx
Traceback (most recent call last):
  File "/usr/local/bin/ofxstatement", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/tool.py", line 195, in run
    return args.func(args)
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/tool.py", line 166, in convert
    statement = parser.parse()
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/plugins/raiffeisen.py", line 27, in parse
    stmt = super(RaiffeisenCsvParser, self).parse()
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/parser.py", line 46, in parse
    stmt_line = self.parse_record(line)
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/plugins/raiffeisen.py", line 46, in parse_record
    stmtline = super(RaiffeisenCsvParser, self).parse_record(line)
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/parser.py", line 107, in parse_record
    value = self.parse_value(rawvalue, field)
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/parser.py", line 66, in parse_value
    return self.parse_datetime(value)
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/parser.py", line 73, in parse_datetime
    return datetime.strptime(value, self.date_format)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '02.01.19' does not match format '%d.%m.%Y'`

maybe my Mac is the issue??

**Comment by nblock** [comment]
Thanks for your report! ELBA may be the culprit here as they (might) have changed the exported files. There are some PRs pending that address ELBA related issues. Once I have access to an ELBA account and get to the PRs, I'll come back to you.
