### ISSUE TITLE
ing-diba doesn't work anymore

### ISSUE THREAD

**Issue by jtrees** [nblock/ofxstatement-austrian#5]
```
$ ofxstatement convert -t ing-diba test.csv out.ofx
Traceback (most recent call last):
  File "/home/josh/.local/bin/ofxstatement", line 11, in <module>
    sys.exit(run())
  File "/home/josh/.local/lib/python3.5/site-packages/ofxstatement/tool.py", line 150, in run
    return args.func(args)
  File "/home/josh/.local/lib/python3.5/site-packages/ofxstatement/tool.py", line 128, in convert
    statement = parser.parse()
  File "/home/josh/.local/lib/python3.5/site-packages/ofxstatement/plugins/ingdiba.py", line 26, in parse
    stmt = super(IngDiBaCsvParser, self).parse()
  File "/home/josh/.local/lib/python3.5/site-packages/ofxstatement/parser.py", line 28, in parse
    stmt_line = self.parse_record(line)
  File "/home/josh/.local/lib/python3.5/site-packages/ofxstatement/plugins/ingdiba.py", line 46, in parse_record
    self.statement.currency = line[3]
IndexError: list index out of range
```

I have included an [anonymised test file](https://github.com/nblock/ofxstatement-austrian/files/1299494/test.csv.txt) for debugging purposes.

I'm using Python 3.5.2 by the way.

**Comment by nblock** [comment]
I just exported the statements from an ING-Diba market money account (Tagesgeld) and worked fine with the latest version. The file you provided looks very different than the statement file I just exported. Are you using a ING-Diba giro account? Currently, only market money accounts are supported for ING-Diba.

**Comment by jtrees** [comment]
Ah, well that's probably the issue then. I am indeed using a giro account.

Perhaps you could update the README to reflect the scope?

**Comment by nblock** [comment]
This is already mentioned in the README.
